package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"

	"github.com/vishnujoshi062/tshirt-ecommerce-api/graph/generated"
	"github.com/vishnujoshi062/tshirt-ecommerce-api/graph/model"
	"github.com/vishnujoshi062/tshirt-ecommerce-api/internal/models"
)

// CreatePromoCode is the resolver for the createPromoCode field.
func (r *mutationResolver) CreatePromoCode(ctx context.Context, input model.PromoCodeInput) (*models.PromoCode, error) {
	return r.Resolver.PromoCodeService.CreatePromoCode(ctx, input)
}

// UpdatePromoCode is the resolver for the updatePromoCode field.
func (r *mutationResolver) UpdatePromoCode(ctx context.Context, id string, input model.PromoCodeInput) (*models.PromoCode, error) {
	return r.Resolver.PromoCodeService.UpdatePromoCode(ctx, id, input)
}

// DeletePromoCode is the resolver for the deletePromoCode field.
func (r *mutationResolver) DeletePromoCode(ctx context.Context, id string) (bool, error) {
	return r.Resolver.PromoCodeService.DeletePromoCode(ctx, id)
}

// TogglePromoCodeStatus is the resolver for the togglePromoCodeStatus field.
func (r *mutationResolver) TogglePromoCodeStatus(ctx context.Context, id string) (*models.PromoCode, error) {
	return r.Resolver.PromoCodeService.ToggleStatus(ctx, id)
}

// ValidFrom is the resolver for the validFrom field.
func (r *promoCodeResolver) ValidFrom(ctx context.Context, obj *models.PromoCode) (*string, error) {
	if obj.ValidFrom == nil {
		return nil, nil
	}
	validFromStr := obj.ValidFrom.String()
	return &validFromStr, nil
}

// ValidUntil is the resolver for the validUntil field.
func (r *promoCodeResolver) ValidUntil(ctx context.Context, obj *models.PromoCode) (*string, error) {
	if obj.ValidUntil == nil {
		return nil, nil
	}
	validUntilStr := obj.ValidUntil.String()
	return &validUntilStr, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *promoCodeResolver) CreatedAt(ctx context.Context, obj *models.PromoCode) (string, error) {
	return obj.CreatedAt.String(), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *promoCodeResolver) UpdatedAt(ctx context.Context, obj *models.PromoCode) (string, error) {
	return obj.UpdatedAt.String(), nil
}

// PromoCodes is the resolver for the promoCodes field.
func (r *queryResolver) PromoCodes(ctx context.Context, isActive *bool) ([]*models.PromoCode, error) {
	return r.Resolver.PromoCodeService.GetAllPromoCodes(ctx)
}

// PromoCode is the resolver for the promoCode field.
func (r *queryResolver) PromoCode(ctx context.Context, code string) (*models.PromoCode, error) {
	return r.Resolver.PromoCodeService.GetPromoCodeByID(ctx, code)
}

// ValidatePromoCode is the resolver for the validatePromoCode field.
func (r *queryResolver) ValidatePromoCode(ctx context.Context, code string, orderAmount float64) (*model.PromoCodeValidation, error) {
	result, err := r.Resolver.PromoCodeService.ValidatePromoCode(code, orderAmount)
	if err != nil {
		return nil, err
	}
	return &model.PromoCodeValidation{
		IsValid:        result.IsValid,
		DiscountAmount: result.DiscountAmount,
		Message:        &result.Message,
	}, nil
}

// PromoCode returns generated.PromoCodeResolver implementation.
func (r *Resolver) PromoCode() generated.PromoCodeResolver { return &promoCodeResolver{r} }

type promoCodeResolver struct{ *Resolver }
