package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"strconv"

	"github.com/vishnujoshi062/tshirt-ecommerce-api/graph/generated"
	"github.com/vishnujoshi062/tshirt-ecommerce-api/graph/model"
	"github.com/vishnujoshi062/tshirt-ecommerce-api/internal/middleware"
	"github.com/vishnujoshi062/tshirt-ecommerce-api/internal/models"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, name *string, phone *string, address *string) (*models.User, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// UpdatePhoneNumber is the resolver for the updatePhoneNumber field.
func (r *mutationResolver) UpdatePhoneNumber(ctx context.Context, input model.UpdatePhoneInput) (*models.User, error) {
	// Get user from context
	claims := middleware.GetUserFromContext(ctx)
	if claims == nil {
		return nil, errors.New("unauthorized: no valid token provided")
	}

	// Validate phone number format (E.164)
	if !isValidE164Phone(input.PhoneNumber) {
		return nil, errors.New("invalid phone number format: must be in E.164 format (e.g., +1234567890)")
	}

	// Update phone number in database
	user, err := r.UserRepository.UpdatePhoneNumber(claims.UserID, input.PhoneNumber)
	if err != nil {
		return nil, fmt.Errorf("failed to update phone number: %w", err)
	}

	return user, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	// Get user from context
	claims := middleware.GetUserFromContext(ctx)
	if claims == nil {
		return nil, errors.New("unauthorized: no valid token provided")
	}

	// Get user from database
	user, err := r.UserRepository.GetUserByID(claims.UserID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	return user, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*models.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// PhoneUpdatedAt is the resolver for the phoneUpdatedAt field.
func (r *userResolver) PhoneUpdatedAt(ctx context.Context, obj *models.User) (*string, error) {
	if obj.PhoneUpdatedAt == nil {
		return nil, nil
	}
	formatted := obj.PhoneUpdatedAt.Format("2006-01-02T15:04:05Z07:00")
	return &formatted, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *models.User) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// isValidE164Phone validates phone number in E.164 format
// E.164 format: +[country code][number] (e.g., +1234567890)
func isValidE164Phone(phone string) bool {
	// E.164 format: + followed by 1-15 digits
	pattern := `^\+[1-9]\d{1,14}$`
	matched, _ := regexp.MatchString(pattern, phone)
	return matched
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
