// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/vishnujoshi062/tshirt-ecommerce-api/internal/models"
)

type AddToCartInput struct {
	CartID    *string `json:"cartId,omitempty"`
	ProductID string  `json:"productId"`
	VariantID *string `json:"variantId,omitempty"`
	Quantity  int     `json:"quantity"`
}

type AddToCartPayload struct {
	Cart *models.Cart `json:"cart"`
}

type AttachCartToUserInput struct {
	CartID string `json:"cartId"`
	UserID string `json:"userId"`
}

type AttachCartToUserPayload struct {
	Cart *models.Cart `json:"cart"`
}

type AuthPayload struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type ClearCartInput struct {
	CartID string `json:"cartId"`
}

type ClearCartPayload struct {
	Cart *models.Cart `json:"cart"`
}

type CreateOrderInput struct {
	ShippingAddress string  `json:"shippingAddress"`
	PromoCode       *string `json:"promoCode,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type ProductInput struct {
	Name             string   `json:"name"`
	Description      *string  `json:"description,omitempty"`
	DesignImageURL   *string  `json:"designImageURL,omitempty"`
	ImageURLs        []string `json:"imageURLs,omitempty"`
	BasePrice        float64  `json:"basePrice"`
	Material         *string  `json:"material,omitempty"`
	Neckline         *string  `json:"neckline,omitempty"`
	SleeveType       *string  `json:"sleeveType,omitempty"`
	Fit              *string  `json:"fit,omitempty"`
	Brand            *string  `json:"brand,omitempty"`
	Category         *string  `json:"category,omitempty"`
	CareInstructions *string  `json:"careInstructions,omitempty"`
	Weight           *float64 `json:"weight,omitempty"`
	Featured         *bool    `json:"featured,omitempty"`
}

type ProductOptions struct {
	Sizes       []string `json:"sizes"`
	Colors      []string `json:"colors"`
	Materials   []string `json:"materials"`
	Necklines   []string `json:"necklines"`
	SleeveTypes []string `json:"sleeveTypes"`
	Fits        []string `json:"fits"`
}

type ProductVariantInput struct {
	ProductID     string  `json:"productID"`
	Size          string  `json:"size"`
	Color         *string `json:"color,omitempty"`
	PriceModifier float64 `json:"priceModifier"`
	Sku           string  `json:"sku"`
	StockQuantity int     `json:"stockQuantity"`
}

type PromoCodeInput struct {
	Code          string              `json:"code"`
	DiscountType  models.DiscountType `json:"discountType"`
	DiscountValue float64             `json:"discountValue"`
	ValidFrom     *string             `json:"validFrom,omitempty"`
	ValidUntil    string              `json:"validUntil"`
	IsActive      *bool               `json:"isActive,omitempty"`
	UsageLimit    *int                `json:"usageLimit,omitempty"`
}

type PromoCodeValidation struct {
	IsValid        bool    `json:"isValid"`
	DiscountAmount float64 `json:"discountAmount"`
	Message        *string `json:"message,omitempty"`
}

type Query struct {
}

type RazorpayOrder struct {
	ID       string  `json:"id"`
	Amount   float64 `json:"amount"`
	Currency string  `json:"currency"`
	Receipt  *string `json:"receipt,omitempty"`
}

type RegisterInput struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Name     string  `json:"name"`
	Phone    *string `json:"phone,omitempty"`
	Address  *string `json:"address,omitempty"`
}

type RemoveCartItemInput struct {
	CartID     string `json:"cartId"`
	CartItemID string `json:"cartItemId"`
}

type RemoveCartItemPayload struct {
	Cart *models.Cart `json:"cart"`
}

type VerifyPaymentInput struct {
	OrderID           string `json:"orderID"`
	RazorpayOrderID   string `json:"razorpayOrderID"`
	RazorpayPaymentID string `json:"razorpayPaymentID"`
	RazorpaySignature string `json:"razorpaySignature"`
}
