// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/vishnujoshi062/tshirt-ecommerce-api/internal/models"
)

type AddToCartInput struct {
	VariantID string `json:"variantID"`
	Quantity  int    `json:"quantity"`
}

type AuthPayload struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type CreateOrderInput struct {
	ShippingAddress string `json:"shippingAddress"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type ProductInput struct {
	Name           string  `json:"name"`
	Description    *string `json:"description,omitempty"`
	DesignImageURL string  `json:"designImageURL"`
	BasePrice      float64 `json:"basePrice"`
}

type ProductVariantInput struct {
	ProductID     string  `json:"productID"`
	Size          string  `json:"size"`
	Color         *string `json:"color,omitempty"`
	PriceModifier float64 `json:"priceModifier"`
	Sku           string  `json:"sku"`
	StockQuantity int     `json:"stockQuantity"`
}

type Query struct {
}

type RazorpayOrder struct {
	ID       string  `json:"id"`
	Amount   float64 `json:"amount"`
	Currency string  `json:"currency"`
	Receipt  *string `json:"receipt,omitempty"`
}

type RegisterInput struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Name     string  `json:"name"`
	Phone    *string `json:"phone,omitempty"`
	Address  *string `json:"address,omitempty"`
}

type VerifyPaymentInput struct {
	OrderID           string `json:"orderID"`
	RazorpayOrderID   string `json:"razorpayOrderID"`
	RazorpayPaymentID string `json:"razorpayPaymentID"`
	RazorpaySignature string `json:"razorpaySignature"`
}
